### ISSUE TITLE
usePackageJsonVersion should generate a valid semver version

### ISSUE THREAD

**Issue by ediblecode** [nhsevidence/teamcity-build-number#16]
Currently the `usePackageJsonVersion` simply appends the build counter to the version from package.json. This means you end up with a build number in the format _Major.Minor.Patch.Counter_ (plus whatever build metadata based on the branch/commit). See https://github.com/nice-digital/teamcity-build-number/blob/master/src/index.js#L39-L40.

This isn't a valid npm SemVer version number (although it is valid with NuGet). This means you can't update the package json with this version, or use it for npm commands like `npm pack` etc. I think though it's valid expectation that using package.json to generate the build number should also result in an npm-semver-compatible version.

You get errors like:

```
npm ERR! Invalid version: "1.0.0.286-rBAF45D4"
```

I propose do one of 3 things to make the generated version valid semver:

1. use the build counter as the patch when `usePackageJsonVersion`  is `true`, overriding the patch value from the package.json
2. use a dash (instead of a dot) to separate the build counter so it becomes part of the meta data e.g. _1.2.3+286.rBAF45D4_  or _1.0.0-298.GN-52-CKSGatsbyv2_
3. append the build counter after the other build metadata e.g. _1.2.3+rBAF45D4.286_ or _1.0.0-GN-52-CKSGatsbyv2.298_

Option 1 disregards whatever is in the patch value for package json, but means we don't have to manually remember to increment patch each time. If you were to add a feature and move from 1.0.whatever to 1.1.whatever you'd potentially jump from 1.0.234 to 1.1.235 which is a bit odd as it implies there are 235 patch releases in version 1.1 which isn't the case!

Option 2, using a dash, actually means that it's treated as a pre-release, so not sure this is the right approach.

Options 3 seems good, however, npm would treat _1.2.3+rBAF45D4.286_ and _1.2.3+rABC123.287_ as the _same_ version as it disregards build metadata (after the plus) so would require manual update to increment major/minor/patch, which, let's be honest we're going to forget to do.

So, on balance, option 1 is probably best. @imranazad @John-Williams  @wa-rren-dev I'd appreciate your thoughts please if you've got a moment! Maybe there's another options I haven't considered?

Run the following to check a version on the command line:

```
npx semver 1.2.3+rBAF45D4.286 || echo "Not valid semver"
npx semver 1.0.0-GN-52-CKSGatsbyv2.298 || echo "Not valid semver"
```

**Comment by imranazad** [comment]
Hey @ediblecode  

Some great rational here. :-)

I'm for option number 1 to remove the need for human intervention. However I wonder what your thoughts are on the patch number increasing with each subsequent build regardless of any code changes? I'm not too keen on that, seems a bit misleading and googling the topic didn't return much opinions other than it appears to be a common practice from what I've seen. 

Regarding the oddness with the versioning, I personally feel the build counter isn't really a true patch number in that it just increments each time a build is triggered so we're not adhering to the "proper conventions" anyway. Therefore I don't think the odd versioning will matter as it would be odd anyway with the incremental patch numbers yet no actual bug fixes.

**Comment by ediblecode** [comment]
Ok, sounds like number 1 is a go. I'll release as a major version so if anyone wants the old behaviour, they can target the previous version.
